loan:
  minAmount: 100.00
  maxAmount: 100000.00
  minTerm: 30
  maxTerm: 360
  extendsionTerm: 30

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false